### ISSUE TITLE
Adding zeroes every time the type is casted

### ISSUE THREAD

**Issue by cdvv7788** [elixirmoney/money#118]
https://github.com/elixirmoney/money/commit/4e633b590fc42b2d110996dbfa1dda8c66036ab9#diff-e4304cf4394e87ec71ae8966845484acR21

I have an input in my form. Let's say I put amount: `42`...it will be cast to `4200`, and if a validation error is raised in my schema, the value is now 4200, not 42.

The library should not add uncalled zeroes to the value. This makes more sense:
![image](https://user-images.githubusercontent.com/5531776/66877316-9cf71d80-ef7a-11e9-9c5e-f0251e8fc026.png)
If I want to save 0.42 in my database, how should I do that? If I want to save 42, how should I do that?

**Comment by Nitrino** [comment]
Hi @cdvv7788 
The library stores the amount in the minimum unit of your currency (it may be different for different currencies). And it affects the calculation and formatting.
Example: 
```elixir
iex(3)> Money.new(42, :USD)
%Money{amount: 42, currency: :USD}
iex(4)> Money.new(42, :USD) |> to_string
"$0.42"
iex(5)> Money.new(42, :USD) |> Money.Currency.exponent
2

iex(6)> Money.new(42, :JPY)
%Money{amount: 42, currency: :JPY}
iex(7)> Money.new(42, :JPY) |> to_string
"¥42"
iex(8)> Money.new(42, :JPY) |> Money.Currency.exponent
0
```

If you want to store 0.42 USD in database you have use `Money.new(42, :USD)`, if want to store 42 USD, use `Money.new(4200, :USD)`.
if you work with floats (I do not recommend performing calculations in floats due to loss of accuracy), then you can use the `parse` method. 
```elixir
iex(17)> Money.parse(0.42, :USD)
{:ok, %Money{amount: 42, currency: :USD}}
iex(18)> Money.parse(42.0, :USD)
{:ok, %Money{amount: 4200, currency: :USD}}
```

If there are any other difficulties, write and I will help to solve them.
