### ISSUE TITLE
Using a column for amount and another for the currency

### ISSUE THREAD

**Issue by michelboaventura** [elixirmoney/money#122]
Hi,

Is there a way to use on Ecto one column for the money amount and another one for the currency, like https://github.com/RubyMoney/money-rails does?

**Comment by Nitrino** [comment]
@michelboaventura 
Hi, unfortunately, you can't do with Ecto like in ruby.

But you can use PostgreSQL custom type 
https://github.com/elixirmoney/money#serialization-to-postgresql-with-multiple-currency

Or serialization to JSON 
https://github.com/elixirmoney/money#serialization-to-database-json-with-multiple-currency

**Comment by michelboaventura** [comment]
@Nitrino, I can't change the database now because I'm migrating the system from rails to elixir, so for a while both will be accessing the same database. But thank you for your time!

**Comment by Nitrino** [comment]
@michelboaventura Then you can create a virtual currency field and write additional workaround when casting and load from the database

**Comment by emaiax** [comment]
hey @Nitrino, I'm struggling with the same approach here, mostly because it's more complex to manage multiple currencies using the `money_with_currency` postgres type. I can't exactly query on that column, nor can apply native postgres functions such as `sum, avg` on the column without creating custom functions to do so. Not even calling `ecto.update_all` to`inc` these columns would be possible. It's a real pain, but I understand that this can't be done because of Ecto limitations by design.

I'm curious about how would be the "load from the database" w/ a virtual money field, can you share some piece of code demonstrating how you accomplish this?
