### ISSUE TITLE
[Question] How do you define a form input in eex for a Money.Ecto.Composite.Type ?

### ISSUE THREAD

**Issue by amilkr** [elixirmoney/money#142]
I have a phoenix application. And I'm updating an ecto schema to have a `Money.Ecto.Composite.Type` field on it. 

I'm not sure how to update my `form.html.eex` to make it work. 
Could someone give me an advice?

It would be nice to have an example in the README

Thanks

**Comment by juanpabloaj** [comment]
@amilkr did you find some way to create a money input?

**Comment by juanpabloaj** [comment]
with this at least I can show and edit the money amount

```
<%= number_input f, :price, value: @product.price.amount %>
```

https://elixirforum.com/t/edit-and-update-using-elixir-money-library/25218/3

**Comment by kuroski** [comment]
I'm also new to the Elixir ecossystem, and this discussion is a bit older now, but here is the way I managed to make it work (maybe it can help someone):

- I followed the installation instructions from the [Serialization to PostgreSQL with multiple currency](https://github.com/elixirmoney/money#serialization-to-postgresql-with-multiple-currency) guide
- I have defined my schema

``` elixir
# lib/myapp/myschema.ex
# ....

schema "myschemas" do
  field :name, :string
  field :price, Money.Ecto.Composite.Type, default: Money.new(0) # I defined the default value as a Money struct to avoid having problems in the form

  timestamps()
end

def changeset(subscription, attrs) do
  subscription
  |> cast(attrs, [
    :name,
    # :price -> I removed price from the cast array, since the form will send a plain "string" basic type representation and since "Composite.Type" is actually a tuple, it can't actually cast it, and you can see that this "Composite.Type" is always expecting a tuple or a map 
  ])
  |> cast_money(attrs, :price) # I created this "cast_money" function to property wrap the "string" comming from the form into a Money struct
  |> validate_required([
    :name,
    # :price -> this won't work because we want to validate the "amount" in the Money struct
  ])
  |> validate_money(:price) # I've created this function following the README documentation about form validation https://hexdocs.pm/money/readme.html#validating-amount-in-ecto-changeset but I changed one small piece of code there
end

defp cast_money(changeset, params, _field) when params == %{}, do: changeset

# here I'm casting the form "text" value into a Money struct 😉 and adding it manually in the changeset
defp cast_money(changeset, params, field) do
  money = field
    |> to_string
    |> (&(Map.get(params, &1))).()
    |> Money.parse
    |> case do
      {:ok, m} -> m
      :error -> field
    end

  put_change(changeset, field, money)
end

defp validate_money(changeset, field) do
  validate_change(changeset, field, fn
    _, %Money{amount: amount} when amount > 0 -> []
    _, _ -> [{ field, "must be greater than 0" }] # I've change that based in the documentation to use the "dynamic" field name instead of a fixed "amount" atom
  end)
end
```

- Now we can just use it in the screen
  - I'm using a generated `form_component.html.leex` by the `mix phx.gen.live` command, but its is basically the same with a plain `eex` template

``` leex
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "myschemas-form",
  class: "text-black",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :price %>
  <%= text_input f, :price %>
  <%= error_tag f, :price %>

  <%= # IO.inspect f %>

  <%= submit "Save", phx_disable_with: "Saving...", class: "button button--primary" %>
</form>
```

The important part here is:
- Make sure you are using a `text_input` for the price field, you can find more information about that in the forum discussions
  - https://elixirforum.com/t/using-number-input-to-accept-money-input-values/28250
  - https://elixirforum.com/t/struggling-with-currency-amount-input-fields-money/33198

I still don't know how to define a "map" or a "struct" as fields using phoenix HTML, but maybe by having that, things can be automated and all code can then be removed since the cast function from `Money.Ecto.Composite.Type` is expecting that structure: https://github.com/elixirmoney/money/blob/master/lib/money/ecto/composite_type.ex#L46

Well... I hope that helps =D 
And thanks for the amazing library!
<3
